### ISSUE TITLE
Cocoapods and Xcode 8, Swift 3 cannot compile

### ISSUE THREAD

**Issue by Majkitos** [krzyzanowskim/CryptoSwift#342]
Hi I am having issue in Xcode 8 and Swift 3. I am using cocoapods and I am pulling from master branch but I am getting 220 Erorrs when I try to build and run my blank project with just installed pods. Does anybody else having this issue as well? Thank you for help!

**Comment by krzyzanowskim** [comment]
Looks like Cococapods have multiple issues with Swift 3 support. Try some of the `pre` versions of cocoapods, it may be fixed.
Most probably SWIFT_VERSION build option is not set and you have to set it manually.

**Comment by Majkitos** [comment]
Thanks for the quick reply! I am currently using cocoapods version 1.1.0.rc.2 without any luck. I will continue trying and I'll let you know once I figure it out.

**Comment by krzyzanowskim** [comment]
Just set it manually, go to pods, find CryptoSwift, and set SWIFT_VERSION configuration from unset to NO.

**Comment by krzyzanowskim** [comment]
also... please ask Cocoapods how to deal with the issue

**Comment by Majkitos** [comment]
OK I have just fixed it. I just needed the pod file looking like this. Thank you for your help and thank you for CryptoSwift! 

```
platform :ios, ‘10.0’
 
inhibit_all_warnings!
use_frameworks!
 
target 'PCF2’ do

pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    	end
  	end
end

```

**Comment by krzyzanowskim** [comment]
Great. it's really good idea to report the issue to Cocoapods repo.

**Comment by Coeur** [comment]
if people are still experiencing issues, don't forget to call `pod deintegrate` before using `pod install` with the custom post_install script.
